version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: gunicorn --workers=4 --bind 0.0.0.0:8000 --reload app:app







